language: python
python:
- 2.6
- 2.7
- 3.2
- 3.3
- pypy
install:
- pip install pytest pytest-cov coveralls
- pip install -e .
script:
- py.test --cov libfeedly --durations=10
after_success:
- coveralls
